### ISSUE TITLE
No message reply after sending the /start command

### ISSUE THREAD

**Issue by Misaka13514** [y-young/nazurin#19]
**Describe the bug**
No message reply after sending the `/start` command.
Other functions seem to work properly.

**To Reproduce**
1. Send `/start` to the bot
2. Wait and receive nothing

**Expected behavior**
The bot will reply `Hi!` before.

**Environment (please complete the following information):**
 - deploy to heroku with default config

**Additional context**
The following is the log of the bot:

```
2021-05-26T13:45:55.542282+00:00 heroku[router]: at=info method=POST path="/1301281176:AAE13v1BWU9QfqQzQItUHHG0jCDsflUWLS0" host=misakapicbot.herokuapp.com request_id=fa275fb5-ddaa-431d-a795-c8a1993a0d74 fwd="91.108.6.58" dyno=web.1 connect=1ms service=46ms status=200 bytes=177 protocol=https
2021-05-26T13:45:56.113117+00:00 app[web.1]: 2021-05-26 13:45:56,111 - nazurin - ERROR - Update {"update_id": 803739853, "message": {"message_id": 5928, "from": {"id": 673435039, "is_bot": false, "first_name": "欠陥電気", "last_name": "𝑹𝒂𝒅𝒊𝒐𝑵𝒐𝒊𝒔𝒆", "username": "Misaka_0x34ca", "language_code": "ja"}, "chat": {"id": 673435039, "first_name": "欠陥電気", "last_name": "𝑹𝒂𝒅𝒊𝒐𝑵𝒐𝒊𝒔𝒆", "username": "Misaka_0x34ca", "type": "private"}, "date": 1622036755, "text": "/start", "entities": [{"type": "bot_command", "offset": 0, "length": 6}]}} caused <class 'aiogram.utils.exceptions.CantParseEntities'>: Can't parse entities: unsupported start tag "id" at byte offset 121
2021-05-26T13:45:56.116012+00:00 app[web.1]: Traceback (most recent call last):
2021-05-26T13:45:56.117958+00:00 app[web.1]: File "/app/nazurin/__main__.py", line 53, in on_error
2021-05-26T13:45:56.117960+00:00 app[web.1]: raise exception
2021-05-26T13:45:56.117991+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/dispatcher/dispatcher.py", line 1340, in process_response
2021-05-26T13:45:56.117991+00:00 app[web.1]: response = task.result()
2021-05-26T13:45:56.120735+00:00 app[web.1]: File "/app/nazurin/utils/decorators.py", line 28, in wrapped_func
2021-05-26T13:45:56.120736+00:00 app[web.1]: result = await asyncio.create_task(func(message, *args, **kwargs))
2021-05-26T13:45:56.138391+00:00 app[web.1]: File "/app/nazurin/__main__.py", line 17, in show_help
2021-05-26T13:45:56.138393+00:00 app[web.1]: await message.reply('''
2021-05-26T13:45:56.145935+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/types/message.py", line 1500, in reply
2021-05-26T13:45:56.145938+00:00 app[web.1]: return await self.bot.send_message(
2021-05-26T13:45:56.145999+00:00 app[web.1]: File "/app/nazurin/utils/decorators.py", line 51, in decorator
2021-05-26T13:45:56.146000+00:00 app[web.1]: result = await func(*args, **kwargs)
2021-05-26T13:45:56.146456+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/bot/bot.py", line 314, in send_message
2021-05-26T13:45:56.146457+00:00 app[web.1]: result = await self.request(api.Methods.SEND_MESSAGE, payload)
2021-05-26T13:45:56.146506+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/bot/base.py", line 208, in request
2021-05-26T13:45:56.146507+00:00 app[web.1]: return await api.make_request(self.session, self.server, self.__token, method, data, files,
2021-05-26T13:45:56.146540+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/bot/api.py", line 140, in make_request
2021-05-26T13:45:56.146541+00:00 app[web.1]: return check_result(method, response.content_type, response.status, await response.text())
2021-05-26T13:45:56.146570+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/bot/api.py", line 115, in check_result
2021-05-26T13:45:56.146571+00:00 app[web.1]: exceptions.BadRequest.detect(description)
2021-05-26T13:45:56.146599+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.8/site-packages/aiogram/utils/exceptions.py", line 140, in detect
2021-05-26T13:45:56.146600+00:00 app[web.1]: raise err(cls.text or description)
2021-05-26T13:45:56.146705+00:00 app[web.1]: aiogram.utils.exceptions.CantParseEntities: Can't parse entities: unsupported start tag "id" at byte offset 121
```

**Comment by Misaka13514** [comment]
I am going to reset token because it leaks in logs. 🤣

**Comment by y-young** [comment]
Fixed, thanks for reporting!
Please take good care of your token 🤣
