### ISSUE TITLE
Onedrive作为存储报错 Cannot create a file without content

### ISSUE THREAD

**Issue by zsbai** [y-young/nazurin#78]
**Describe the bug**
Onedrive作为存储，成功创建了文件夹，但是报错无法上传文件，telegram bot回复“Response Error: 400 Bad Request“
```
2023-06-07 10:13:21,291-0400 - INFO     - nazurin.middleware:25 - update:658614568 - Message 490: https://twitter.com/pieleaf_x2/status/1656239069461102592?s=46&t=sRguD45342wIFRmICSHhQw
2023-06-07 10:13:21,294-0400 - INFO     - nazurin.bot:123 - update:658614568 - Collection update: site=twitter, match=('1656239069461102592',)
2023-06-07 10:13:21,306-0400 - INFO     - nazurin.sites.twitter.api.web:114 - update:658614568 - Fetching tweet 1656239069461102592 from web API
2023-06-07 10:13:21,318-0400 - INFO     - aiohttp.web_log:206 -  - 127.0.0.1 "POST /923219210:AJSMNNWJDSzsdsaAOOQOPWEnkajsd HTTP/1.0" 200 152 "-" "-"
2023-06-07 10:13:23,163-0400 - INFO     - nazurin.storage.onedrive:66 - update:658614568 - Creating folders: {PosixPath('Nazurin/Twitter')}
2023-06-07 10:13:23,167-0400 - INFO     - nazurin.storage.onedrive:37 - update:658614568 - Creating drive item...
2023-06-07 10:13:24,063-0400 - ERROR    - nazurin.storage.onedrive:192 - update:658614568 - {"error":{"code":"invalidRequest","message":"Cannot create a file without content","innerError":{"date":"2023-06-07T14:11:07","request-id":"3ac0xxxxxx","client-request-id":"3ac02xxxxxx"}}}
Traceback (most recent call last):
  File "/root/nazurin/nazurin/__main__.py", line 91, in on_error
    raise exception
  File "/usr/local/lib/python3.9/dist-packages/aiogram/dispatcher/dispatcher.py", line 1394, in process_response
    response = task.result()
  File "/root/nazurin/nazurin/dispatcher.py", line 119, in update_collection
    await self.bot.update_collection(urls, message)
  File "/root/nazurin/nazurin/bot.py", line 157, in update_collection
    await self.storage.store(illust)
  File "/root/nazurin/nazurin/storage/__init__.py", line 26, in store
    await asyncio.gather(*tasks)
  File "/root/nazurin/nazurin/storage/onedrive.py", line 70, in store
    await asyncio.gather(*tasks)
  File "/root/nazurin/nazurin/storage/onedrive.py", line 49, in upload
    response = await self._request("POST", create_file_url, json=body)
  File "/usr/local/lib/python3.9/dist-packages/tenacity/_asyncio.py", line 48, in call
    do = self.iter(retry_state=retry_state)
  File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 320, in iter
    return fut.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/dist-packages/tenacity/_asyncio.py", line 51, in call
    result = yield from fn(*args, **kwargs)
  File "/root/nazurin/nazurin/storage/onedrive.py", line 193, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/dist-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://graph.microsoft.com/v1.0/me/drive/items/root:/Nazurin/Twitter:/children')
```

**Expected behavior**
正常上传图片，然而只是创建了文件夹

**Environment (please complete the following information):**
Linux debian 5.10.0-18-amd64 #1 SMP Debian 5.10.140-1 (2022-09-02) x86_64 GNU/Linux
Python 3.9.2

**Additional context**
同时如果我更换了onedrive的client ID和secret，数据库并不会自己更新，一直会尝试用旧的....手动去删除了数据库中的onedrive才能使用本地.env中的新client ID和secret

**Comment by y-young** [comment]
有可能是因为图片没有下载成功，可以到 `data/temp` 里看一下，或者把 `data/temp` 清空再重试一次

> 同时如果我更换了onedrive的client ID和secret，数据库并不会自己更新，一直会尝试用旧的....手动去删除了数据库中的onedrive才能使用本地.env中的新client ID和secret

这个应该是 Access Token 没有更新，修改了 Client ID 和 Secret 之后需要手动删除

另外，你的 Bot Token 泄露了，记得重置一下

**Comment by y-young** [comment]
我这边无法复现，需要更多信息

如果方便的话到这个文件里把这一行
https://github.com/y-young/nazurin/blob/16d3ca41b0c571daa1a64c0464ec65bdc55fb5c4/nazurin/storage/onedrive.py#L41

改成这样：
```python
        size = await file.size()
        logger.info("File: {}", file)
```

然后重启 Bot，重试一次，把新的日志贴上来（记得把 Bot Token `923219210:AJSMNNW` 删掉）

另外我看到你在 #48 也用了 OneDrive，当时是同一个网盘而且没有问题？大概是什么时候出现问题的？

**Comment by y-young** [comment]
> 之前一直是可以正常上传的，由于之前E5大清理嘛，我的Onedrive就更换到了自己的号上，然后就出现了之前说的bot一直用旧的client ID导致启动不起来

如果更换了账号需要用个人账号在 Azure Active Directory 重新注册应用，rclone 用这套应用凭据能正常使用吗？

**Comment by y-young** [comment]
稍微重构了一下上传的函数，可以用 [refactor/onedrive-upload](https://github.com/y-young/nazurin/tree/refactor/onedrive-upload) 分支试试

**Comment by y-young** [comment]
Fixed in https://github.com/y-young/nazurin/commit/21031894f487362219d09c7fdd4f516734d91269 .
